version: '3.4'

services:
  kvs:
    container_name: kvs-container
    image: ${DOCKER_REGISTRY-}kvs
    build:
      context: .
      dockerfile: KVS/Dockerfile
    ports:
      - 80:80
      - 443:443 

  postgres:
    container_name: postgres-container
    image: postgres
    environment:
      # TODO: Use the POSTGRES_PASSWORD_FILE environment variable so that the password isn't commited
      POSTGRES_PASSWORD: temppw
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    volumes:
      - db-data:/var/lib/postgres/data

  rabbit-mq:
    container_name: rabbit-mq-container
    image: rabbitmq:management
    ports:
      - 8080:15672
    environment:
      # TODO: Use a rabbitmq configuration file, https://www.rabbitmq.com/docs/configure, for the same reasons as postgres
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbit-mq-data:/var/lib/rabbitmq

volumes:
  db-data:
    name: kvs-db-data
  rabbit-mq-data:
    name: kvs-rabbit-mq-data
      