name: Build and Test

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore KVS.sln
    - name: Build
      run: dotnet build --no-restore KVS.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal KVS.sln
